config/routes.rb
Rails.application.routes.draw do
  resources :channels do
    resource :channel_user # Singular, if we want to create/delete a user channel, we will operate on the current user without passin an extra ID for the user itself.
    resources :messages
  end

  devise_for :users

  root to: 'channels#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :channel_users, dependent: :destroy
  has_many :users, through: :channel_users
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/channel_user.rb
class ChannelUser < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :channel_users, dependent: :destroy
  has_many :channels, through: :channel_users
  has_many :messages, dependent: :destroy
end

app/controllers/MessagesController.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_channel

  def create
    @message = @channel.messages.create message_params
  end

  private 
    def set_channel
      @channel = current_user.channels.find params[:channel_id] # inforce the user is a member of the channel
    end

    def message_params
      params.require(:message).permit(:body).merge user: current_user
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channel_users_controller.rb
class ChannelUsersController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_channel

  def create
    @channel.channel_users.where(user: current_user).first_or_create
    redirect_to @channel
  end

  def destroy
    @channel.channel_users.where(user: current_user).destroy_all
    redirect_to @channel
  end

  private
    def set_channel
      @channel = Channel.find params[:channel_id]
    end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_channel, only: %i[ show edit update destroy ]

  # GET /channels or /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1 or /channels/1.json
  def show
    @channel_user = current_user.channel_users.find_by channel: @channel
    @last_read_at = @channel_user&.last_read_at || @channel.created_at # to not deal with nils
    @channel_user&.touch :last_read_at
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels or /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: "Channel was successfully created." }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1 or /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: "Channel was successfully updated." }
        format.json { render :show, status: :ok, location: @channel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1 or /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: "Channel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_channel

  def create
    @message = @channel.messages.create message_params
    MessageChannel.broadcast_to @channel, message: render_to_string(@message)
    UnreadsChannel.broadcast_to @channel, {}
  end

  private 
    def set_channel
      @channel = current_user.channels.find params[:channel_id] # inforce the user is a member of the channel
    end

    def message_params
      params.require(:message).permit(:body).merge user: current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: channel) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<div data-controller='channel' data-channel-id='<%= @channel.id %>' class='grid grid-cols-4 gap-6'>
  <div class='col-span-1'>
    <div class='mb-2 flex justify-between items-center'>
      <h3 class='inline'>Channels</h3>
      <%= link_to fa_icon('plus'), new_channel_path %>
    </div>

    <% Channel.all.each do |channel| %>
      <div class='mb-2 flex justify-between items-center'>
        <%= link_to channel.name, channel, data: { controller: 'unreads', unreads_id: channel.id } %>
        <% if current_user.channels.include?(channel) %>
          <%= link_to fa_icon('times', class: 'text-red-400'), channel_channel_user_path(channel), method: :delete %> 
        <% end %>
      </div>
    <% end %>
    <div>
      <h3>Users</h3>
    </div>
    <% @channel.users.each do |user| %>
      <div>
        <%= user.email %>
      </div>
    <% end %>

  </div>
  <div class='col-span-3 pt-6'>
    <div data-channel-target='messages'>
      <%= render @channel.messages %>
    </div>

    <% if current_user.channels.include?(@channel) %>
      <%= form_with model: [@channel, Message.new], data: { remote: true, action: 'ajax:success->channel#clearMessage' } do |form| %>
        <%= form.text_field :body, data: { 'channel-target': 'newMessage' } %>
      <% end %>
    <% else %>
      <%= link_to "Join #{@channel.name}", channel_channel_user_path(@channel), method: :post %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupChatWithActionCable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class='my-2'>
  <% if !@bar_shown && @last_read_at && message.created_at > @last_read_at %>
    <% @bar_shown = true %>
    <div class="border-b border-1 border-red-500"></div>
  <% end %>

  <div><b><%= message.user.email %></b></div>
  <div><%= message.body %></div>
</div>